### PR TITLE
Add Fonts to Googleam via Google Fonts and CSS

### PR DESCRIPTION
**Pull request by devilAPI**

### CODE REVIEW

**Comment by devilAPI** [comment]
https://fonts.google.com/specimen/Roboto?selection.family=Roboto:wght@100;700&sidebar.open

**Comment by devilAPI** [comment]
googleamsearch
googleam

**Review by devilAPI — COMMENTED** [review]
Formatting

**Comment by Mubelotix** [comment]
Actually I am not convinced with this font. It is too thin with the dark theme. I will change it

**Comment by Mubelotix** [comment]
I switched to Lato. I chose this font because it's the font used by gleam.io.

**Pull request merged**
